name: Test

on: [push]

jobs:
  
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, win-latest, macOS-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
        path: ~/go/pkg/mod
        key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
